apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-12-20T14:25:20Z"
  generation: 2
  labels:
    k8s-app: api
  name: api
  namespace: default
  resourceVersion: "59537"
  selfLink: /apis/apps/v1/namespaces/default/deployments/api
  uid: ff057b40-8eef-4f2b-af72-b485af42da9d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: api
      name: api
    spec:
      containers:
      - image: fabmedicalmc0.azurecr.io/content-api
        env:
        - name: MONGODB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: cosmosdb
              key: db
        imagePullPolicy: Always
        name: api
        resources:
          requests:
            cpu: "1"
            memory: 128Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-12-20T14:25:20Z"
    lastUpdateTime: "2020-12-20T14:28:35Z"
    message: ReplicaSet "api-67df4cc99f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-12-20T14:34:39Z"
    lastUpdateTime: "2020-12-20T14:34:39Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 2
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
